/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as goldBardTokenSol from "./GoldBardToken.sol";
export type { goldBardTokenSol };
import type * as monokumaSol from "./Monokuma.sol";
export type { monokumaSol };
export type { CopperBarToken } from "./CopperBarToken";
export type { SilverBarToken } from "./SilverBarToken";
