/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from "./IERC20";
export type { IFactoryV2 } from "./IFactoryV2";
export type { IRouter01 } from "./IRouter01";
export type { IRouter02 } from "./IRouter02";
export type { IV2Pair } from "./IV2Pair";
export type { Monokuma } from "./Monokuma";
export type { Protections } from "./Protections";
