/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as goldBardTokenSol from "./GoldBardToken.sol";
export * as monokumaSol from "./Monokuma.sol";
export { CopperBarToken__factory } from "./CopperBarToken__factory";
export { SilverBarToken__factory } from "./SilverBarToken__factory";
