/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "CopperBarToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CopperBarToken__factory>;
    getContractFactory(
      name: "GoldBarToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GoldBarToken__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "IFactoryV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFactoryV2__factory>;
    getContractFactory(
      name: "IRouter01",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRouter01__factory>;
    getContractFactory(
      name: "IRouter02",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRouter02__factory>;
    getContractFactory(
      name: "IV2Pair",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IV2Pair__factory>;
    getContractFactory(
      name: "Monokuma",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Monokuma__factory>;
    getContractFactory(
      name: "Protections",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Protections__factory>;
    getContractFactory(
      name: "SilverBarToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SilverBarToken__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "CopperBarToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CopperBarToken>;
    getContractAt(
      name: "GoldBarToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.GoldBarToken>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "IFactoryV2",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IFactoryV2>;
    getContractAt(
      name: "IRouter01",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IRouter01>;
    getContractAt(
      name: "IRouter02",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IRouter02>;
    getContractAt(
      name: "IV2Pair",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IV2Pair>;
    getContractAt(
      name: "Monokuma",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Monokuma>;
    getContractAt(
      name: "Protections",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Protections>;
    getContractAt(
      name: "SilverBarToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SilverBarToken>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
